ALTER TABLE users
  ADD COLUMN IF NOT EXISTS plan VARCHAR(20) NOT NULL DEFAULT 'free',
  ADD COLUMN IF NOT EXISTS quota_seconds INTEGER NOT NULL DEFAULT 1800,
  ADD COLUMN IF NOT EXISTS quota_alert_seconds INTEGER NOT NULL DEFAULT 300,
  ADD COLUMN IF NOT EXISTS plan_started_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS plan_expires_at TIMESTAMP WITH TIME ZONE;

ALTER TABLE transcriptions
  ADD COLUMN IF NOT EXISTS processing_seconds NUMERIC;
