import type {
  AdminSettings,
  AdminUser,
  AuditLog,
  ManagedFile,
  TranscriptionJob,
} from "./types";

const now = Date.now();
const daysAgo = (days: number, hour = 9) =>
  new Date(
    now - days * 24 * 60 * 60 * 1000 + hour * 60 * 60 * 1000,
  ).toISOString();

export const adminUsers: AdminUser[] = [
  {
    id: "usr_001",
    name: "Nguyen Minh Anh",
    email: "minhanh@example.com",
    role: "admin",
    status: "active",
    quota_minutes: 1200,
    used_minutes: 842,
    created_at: daysAgo(34),
    last_login_at: daysAgo(0, 3),
  },
  {
    id: "usr_002",
    name: "Tran Hoang Nam",
    email: "nam.tran@example.com",
    role: "viewer",
    status: "active",
    quota_minutes: 300,
    used_minutes: 286,
    created_at: daysAgo(18),
    last_login_at: daysAgo(1, 1),
  },
  {
    id: "usr_003",
    name: "Le Thu Ha",
    email: "ha.le@example.com",
    role: "admin",
    status: "suspended",
    quota_minutes: 600,
    used_minutes: 118,
    created_at: daysAgo(56),
    last_login_at: daysAgo(12),
  },
  {
    id: "usr_004",
    name: "Pham Quoc Viet",
    email: "viet.pham@example.com",
    role: "viewer",
    status: "active",
    quota_minutes: 900,
    used_minutes: 421,
    created_at: daysAgo(8),
    last_login_at: daysAgo(2),
  },
  {
    id: "usr_005",
    name: "Bui Linh Chi",
    email: "linhchi@example.com",
    role: "super_admin",
    status: "active",
    quota_minutes: 1800,
    used_minutes: 1210,
    created_at: daysAgo(90),
    last_login_at: daysAgo(0, 1),
  },
  {
    id: "usr_006",
    name: "Do Gia Bao",
    email: "bao.do@example.com",
    role: "viewer",
    status: "deleted",
    quota_minutes: 120,
    used_minutes: 54,
    created_at: daysAgo(120),
    last_login_at: null,
  },
];

export const transcriptionJobs: TranscriptionJob[] = [
  {
    job_id: "job_8N2QK1",
    user_id: "usr_001",
    user_name: "Nguyen Minh Anh",
    user_email: "minhanh@example.com",
    file_id: "file_001",
    file_name: "weekly-meeting.mp3",
    language: "vi",
    duration: 1840,
    status: "completed",
    processing_time: 214,
    created_at: daysAgo(0, 2),
    completed_at: daysAgo(0, 2),
    transcript: "Nội dung cuộc họp tuần đã được nhận diện và phân đoạn.",
  },
  {
    job_id: "job_2KJ9AA",
    user_id: "usr_002",
    user_name: "Tran Hoang Nam",
    user_email: "nam.tran@example.com",
    file_id: "file_002",
    file_name: "interview-founder.mp4",
    language: "en",
    duration: 2460,
    status: "failed",
    processing_time: 78,
    created_at: daysAgo(0, 4),
    completed_at: daysAgo(0, 4),
    error_message: "Media stream has no readable audio track.",
  },
  {
    job_id: "job_4PL1Z0",
    user_id: "usr_003",
    user_name: "Le Thu Ha",
    user_email: "ha.le@example.com",
    file_id: "file_003",
    file_name: "sales-call.wav",
    language: "vi",
    duration: 650,
    status: "queued",
    processing_time: null,
    created_at: daysAgo(1, 5),
    completed_at: null,
  },
  {
    job_id: "job_7MX8QW",
    user_id: "usr_004",
    user_name: "Pham Quoc Viet",
    user_email: "viet.pham@example.com",
    file_id: "file_004",
    file_name: "webinar-clip.m4a",
    language: "ja",
    duration: 3100,
    status: "processing",
    processing_time: null,
    created_at: daysAgo(1, 2),
    completed_at: null,
  },
  {
    job_id: "job_3CAB92",
    user_id: "usr_005",
    user_name: "Bui Linh Chi",
    user_email: "linhchi@example.com",
    file_id: "file_005",
    file_name: "support-training.mp3",
    language: "vi",
    duration: 920,
    status: "cancelled",
    processing_time: 12,
    created_at: daysAgo(2),
    completed_at: daysAgo(2),
  },
  {
    job_id: "job_9QP0LD",
    user_id: "usr_001",
    user_name: "Nguyen Minh Anh",
    user_email: "minhanh@example.com",
    file_id: "file_006",
    file_name: "podcast-episode.mp3",
    language: "en",
    duration: 4200,
    status: "completed",
    processing_time: 398,
    created_at: daysAgo(3),
    completed_at: daysAgo(3),
    transcript: "Podcast transcript result with speaker turns and timestamps.",
  },
];

export const managedFiles: ManagedFile[] = [
  {
    file_id: "file_001",
    file_name: "weekly-meeting.mp3",
    owner_id: "usr_001",
    owner_name: "Nguyen Minh Anh",
    owner_email: "minhanh@example.com",
    file_type: "audio",
    file_size: 32_400_000,
    duration_seconds: 1840,
    storage_status: "available",
    transcription_status: "completed",
    created_at: daysAgo(0, 2),
    media_url: "",
    has_audio_track: true,
    metadata: { channels: 2, bitrate: "192kbps", source: "web" },
  },
  {
    file_id: "file_002",
    file_name: "interview-founder.mp4",
    owner_id: "usr_002",
    owner_name: "Tran Hoang Nam",
    owner_email: "nam.tran@example.com",
    file_type: "video",
    file_size: 245_000_000,
    duration_seconds: 2460,
    storage_status: "error",
    transcription_status: "failed",
    created_at: daysAgo(0, 4),
    media_url: "",
    has_audio_track: false,
    metadata: { resolution: "1080p", codec: "h264", source: "api" },
  },
  {
    file_id: "file_003",
    file_name: "sales-call.wav",
    owner_id: "usr_003",
    owner_name: "Le Thu Ha",
    owner_email: "ha.le@example.com",
    file_type: "audio",
    file_size: 58_100_000,
    duration_seconds: 650,
    storage_status: "available",
    transcription_status: "queued",
    created_at: daysAgo(1, 5),
    media_url: "",
    has_audio_track: true,
    metadata: { channels: 1, sample_rate: 44100, source: "web" },
  },
  {
    file_id: "file_004",
    file_name: "webinar-clip.m4a",
    owner_id: "usr_004",
    owner_name: "Pham Quoc Viet",
    owner_email: "viet.pham@example.com",
    file_type: "audio",
    file_size: 84_200_000,
    duration_seconds: 3100,
    storage_status: "archived",
    transcription_status: "processing",
    created_at: daysAgo(1, 2),
    media_url: "",
    has_audio_track: true,
    metadata: { channels: 2, source: "web" },
  },
];

export let adminSettings: AdminSettings = {
  max_file_size_mb: 500,
  max_file_duration_minutes: 180,
  supported_formats: ["mp3", "wav", "m4a", "mp4", "mov"],
  supported_languages: ["vi", "en", "ja", "ko", "zh"],
  max_retry_attempts: 3,
  default_quota_minutes: 300,
  storage_policy: "keep_transcripts_and_media",
  data_retention_days: 365,
  system_parameters: {
    queue_concurrency: 1,
    queue_retention_ms: 3600000,
  },
  notification_config: {
    usage_alert_email: true,
    failure_alert_email: false,
  },
};

export const auditLogs: AuditLog[] = [
  {
    id: "aud_001",
    actor: "Bui Linh Chi",
    action: "quota.adjust",
    target_type: "quota",
    target_id: "usr_002",
    details: { delta_minutes: 100, reason: "Gia hạn dùng thử" },
    created_at: daysAgo(0, 1),
  },
  {
    id: "aud_002",
    actor: "Nguyen Minh Anh",
    action: "transcription.retry",
    target_type: "transcription",
    target_id: "job_2KJ9AA",
    details: { previous_status: "failed" },
    created_at: daysAgo(0, 3),
  },
  {
    id: "aud_003",
    actor: "Bui Linh Chi",
    action: "user.suspend",
    target_type: "user",
    target_id: "usr_003",
    details: { reason: "Billing review" },
    created_at: daysAgo(2),
  },
];

export function replaceAdminSettings(next: AdminSettings) {
  adminSettings = next;
}
