/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as TranscriptionSettingsRouteImport } from './routes/transcription-settings'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RecordRouteImport } from './routes/record'
import { Route as RealtimeRouteImport } from './routes/realtime'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CustomDictionaryRouteImport } from './routes/custom-dictionary'
import { Route as ApiRouteImport } from './routes/api'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutOrderIdRouteImport } from './routes/checkout.$orderId'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const TranscriptionSettingsRoute = TranscriptionSettingsRouteImport.update({
  id: '/transcription-settings',
  path: '/transcription-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordRoute = RecordRouteImport.update({
  id: '/record',
  path: '/record',
  getParentRoute: () => rootRouteImport,
} as any)
const RealtimeRoute = RealtimeRouteImport.update({
  id: '/realtime',
  path: '/realtime',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomDictionaryRoute = CustomDictionaryRouteImport.update({
  id: '/custom-dictionary',
  path: '/custom-dictionary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoute = ApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutOrderIdRoute = CheckoutOrderIdRouteImport.update({
  id: '/checkout/$orderId',
  path: '/checkout/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api': typeof ApiRoute
  '/custom-dictionary': typeof CustomDictionaryRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/realtime': typeof RealtimeRoute
  '/record': typeof RecordRoute
  '/register': typeof RegisterRoute
  '/transcription-settings': typeof TranscriptionSettingsRoute
  '/upload': typeof UploadRoute
  '/checkout/$orderId': typeof CheckoutOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api': typeof ApiRoute
  '/custom-dictionary': typeof CustomDictionaryRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/realtime': typeof RealtimeRoute
  '/record': typeof RecordRoute
  '/register': typeof RegisterRoute
  '/transcription-settings': typeof TranscriptionSettingsRoute
  '/upload': typeof UploadRoute
  '/checkout/$orderId': typeof CheckoutOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api': typeof ApiRoute
  '/custom-dictionary': typeof CustomDictionaryRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/realtime': typeof RealtimeRoute
  '/record': typeof RecordRoute
  '/register': typeof RegisterRoute
  '/transcription-settings': typeof TranscriptionSettingsRoute
  '/upload': typeof UploadRoute
  '/checkout/$orderId': typeof CheckoutOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api'
    | '/custom-dictionary'
    | '/dashboard'
    | '/history'
    | '/login'
    | '/pricing'
    | '/profile'
    | '/realtime'
    | '/record'
    | '/register'
    | '/transcription-settings'
    | '/upload'
    | '/checkout/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api'
    | '/custom-dictionary'
    | '/dashboard'
    | '/history'
    | '/login'
    | '/pricing'
    | '/profile'
    | '/realtime'
    | '/record'
    | '/register'
    | '/transcription-settings'
    | '/upload'
    | '/checkout/$orderId'
  id:
    | '__root__'
    | '/'
    | '/api'
    | '/custom-dictionary'
    | '/dashboard'
    | '/history'
    | '/login'
    | '/pricing'
    | '/profile'
    | '/realtime'
    | '/record'
    | '/register'
    | '/transcription-settings'
    | '/upload'
    | '/checkout/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiRoute: typeof ApiRoute
  CustomDictionaryRoute: typeof CustomDictionaryRoute
  DashboardRoute: typeof DashboardRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  ProfileRoute: typeof ProfileRoute
  RealtimeRoute: typeof RealtimeRoute
  RecordRoute: typeof RecordRoute
  RegisterRoute: typeof RegisterRoute
  TranscriptionSettingsRoute: typeof TranscriptionSettingsRoute
  UploadRoute: typeof UploadRoute
  CheckoutOrderIdRoute: typeof CheckoutOrderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transcription-settings': {
      id: '/transcription-settings'
      path: '/transcription-settings'
      fullPath: '/transcription-settings'
      preLoaderRoute: typeof TranscriptionSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/record': {
      id: '/record'
      path: '/record'
      fullPath: '/record'
      preLoaderRoute: typeof RecordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/realtime': {
      id: '/realtime'
      path: '/realtime'
      fullPath: '/realtime'
      preLoaderRoute: typeof RealtimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-dictionary': {
      id: '/custom-dictionary'
      path: '/custom-dictionary'
      fullPath: '/custom-dictionary'
      preLoaderRoute: typeof CustomDictionaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api': {
      id: '/api'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof ApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$orderId': {
      id: '/checkout/$orderId'
      path: '/checkout/$orderId'
      fullPath: '/checkout/$orderId'
      preLoaderRoute: typeof CheckoutOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiRoute: ApiRoute,
  CustomDictionaryRoute: CustomDictionaryRoute,
  DashboardRoute: DashboardRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  ProfileRoute: ProfileRoute,
  RealtimeRoute: RealtimeRoute,
  RecordRoute: RecordRoute,
  RegisterRoute: RegisterRoute,
  TranscriptionSettingsRoute: TranscriptionSettingsRoute,
  UploadRoute: UploadRoute,
  CheckoutOrderIdRoute: CheckoutOrderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
