/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as TranscriptionSettingsRouteImport } from './routes/transcription-settings'
import { Route as SupportRouteImport } from './routes/support'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ReferralRouteImport } from './routes/referral'
import { Route as RecordRouteImport } from './routes/record'
import { Route as RealtimeRouteImport } from './routes/realtime'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CustomDictionaryRouteImport } from './routes/custom-dictionary'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ApiRouteImport } from './routes/api'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as CheckoutOrderIdRouteImport } from './routes/checkout.$orderId'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminUsageRouteImport } from './routes/admin.usage'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminProvidersRouteImport } from './routes/admin.providers'
import { Route as AdminPlansRouteImport } from './routes/admin.plans'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminJobsRouteImport } from './routes/admin.jobs'
import { Route as AdminFilesRouteImport } from './routes/admin.files'
import { Route as AdminAuditLogsRouteImport } from './routes/admin.audit-logs'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const TranscriptionSettingsRoute = TranscriptionSettingsRouteImport.update({
  id: '/transcription-settings',
  path: '/transcription-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralRoute = ReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordRoute = RecordRouteImport.update({
  id: '/record',
  path: '/record',
  getParentRoute: () => rootRouteImport,
} as any)
const RealtimeRoute = RealtimeRouteImport.update({
  id: '/realtime',
  path: '/realtime',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomDictionaryRoute = CustomDictionaryRouteImport.update({
  id: '/custom-dictionary',
  path: '/custom-dictionary',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoute = ApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const CheckoutOrderIdRoute = CheckoutOrderIdRouteImport.update({
  id: '/checkout/$orderId',
  path: '/checkout/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsageRoute = AdminUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProvidersRoute = AdminProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlansRoute = AdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJobsRoute = AdminJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFilesRoute = AdminFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/api': typeof ApiRoute
  '/contact': typeof ContactRoute
  '/custom-dictionary': typeof CustomDictionaryRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/realtime': typeof RealtimeRoute
  '/record': typeof RecordRoute
  '/referral': typeof ReferralRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/support': typeof SupportRoute
  '/transcription-settings': typeof TranscriptionSettingsRoute
  '/upload': typeof UploadRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/files': typeof AdminFilesRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/providers': typeof AdminProvidersRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/usage': typeof AdminUsageRoute
  '/admin/users': typeof AdminUsersRoute
  '/checkout/$orderId': typeof CheckoutOrderIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api': typeof ApiRoute
  '/contact': typeof ContactRoute
  '/custom-dictionary': typeof CustomDictionaryRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/realtime': typeof RealtimeRoute
  '/record': typeof RecordRoute
  '/referral': typeof ReferralRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/support': typeof SupportRoute
  '/transcription-settings': typeof TranscriptionSettingsRoute
  '/upload': typeof UploadRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/files': typeof AdminFilesRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/providers': typeof AdminProvidersRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/usage': typeof AdminUsageRoute
  '/admin/users': typeof AdminUsersRoute
  '/checkout/$orderId': typeof CheckoutOrderIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/api': typeof ApiRoute
  '/contact': typeof ContactRoute
  '/custom-dictionary': typeof CustomDictionaryRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/realtime': typeof RealtimeRoute
  '/record': typeof RecordRoute
  '/referral': typeof ReferralRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/support': typeof SupportRoute
  '/transcription-settings': typeof TranscriptionSettingsRoute
  '/upload': typeof UploadRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/files': typeof AdminFilesRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/providers': typeof AdminProvidersRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/usage': typeof AdminUsageRoute
  '/admin/users': typeof AdminUsersRoute
  '/checkout/$orderId': typeof CheckoutOrderIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/api'
    | '/contact'
    | '/custom-dictionary'
    | '/dashboard'
    | '/forgot-password'
    | '/history'
    | '/login'
    | '/pricing'
    | '/realtime'
    | '/record'
    | '/referral'
    | '/register'
    | '/reset-password'
    | '/support'
    | '/transcription-settings'
    | '/upload'
    | '/admin/audit-logs'
    | '/admin/files'
    | '/admin/jobs'
    | '/admin/login'
    | '/admin/plans'
    | '/admin/providers'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/usage'
    | '/admin/users'
    | '/checkout/$orderId'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/api'
    | '/contact'
    | '/custom-dictionary'
    | '/dashboard'
    | '/forgot-password'
    | '/history'
    | '/login'
    | '/pricing'
    | '/realtime'
    | '/record'
    | '/referral'
    | '/register'
    | '/reset-password'
    | '/support'
    | '/transcription-settings'
    | '/upload'
    | '/admin/audit-logs'
    | '/admin/files'
    | '/admin/jobs'
    | '/admin/login'
    | '/admin/plans'
    | '/admin/providers'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/usage'
    | '/admin/users'
    | '/checkout/$orderId'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/api'
    | '/contact'
    | '/custom-dictionary'
    | '/dashboard'
    | '/forgot-password'
    | '/history'
    | '/login'
    | '/pricing'
    | '/realtime'
    | '/record'
    | '/referral'
    | '/register'
    | '/reset-password'
    | '/support'
    | '/transcription-settings'
    | '/upload'
    | '/admin/audit-logs'
    | '/admin/files'
    | '/admin/jobs'
    | '/admin/login'
    | '/admin/plans'
    | '/admin/providers'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/usage'
    | '/admin/users'
    | '/checkout/$orderId'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ApiRoute: typeof ApiRoute
  ContactRoute: typeof ContactRoute
  CustomDictionaryRoute: typeof CustomDictionaryRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  RealtimeRoute: typeof RealtimeRoute
  RecordRoute: typeof RecordRoute
  ReferralRoute: typeof ReferralRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SupportRoute: typeof SupportRoute
  TranscriptionSettingsRoute: typeof TranscriptionSettingsRoute
  UploadRoute: typeof UploadRoute
  CheckoutOrderIdRoute: typeof CheckoutOrderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transcription-settings': {
      id: '/transcription-settings'
      path: '/transcription-settings'
      fullPath: '/transcription-settings'
      preLoaderRoute: typeof TranscriptionSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referral': {
      id: '/referral'
      path: '/referral'
      fullPath: '/referral'
      preLoaderRoute: typeof ReferralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/record': {
      id: '/record'
      path: '/record'
      fullPath: '/record'
      preLoaderRoute: typeof RecordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/realtime': {
      id: '/realtime'
      path: '/realtime'
      fullPath: '/realtime'
      preLoaderRoute: typeof RealtimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-dictionary': {
      id: '/custom-dictionary'
      path: '/custom-dictionary'
      fullPath: '/custom-dictionary'
      preLoaderRoute: typeof CustomDictionaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api': {
      id: '/api'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof ApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/checkout/$orderId': {
      id: '/checkout/$orderId'
      path: '/checkout/$orderId'
      fullPath: '/checkout/$orderId'
      preLoaderRoute: typeof CheckoutOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/usage': {
      id: '/admin/usage'
      path: '/usage'
      fullPath: '/admin/usage'
      preLoaderRoute: typeof AdminUsageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/providers': {
      id: '/admin/providers'
      path: '/providers'
      fullPath: '/admin/providers'
      preLoaderRoute: typeof AdminProvidersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/plans': {
      id: '/admin/plans'
      path: '/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AdminPlansRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/jobs': {
      id: '/admin/jobs'
      path: '/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AdminJobsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/files': {
      id: '/admin/files'
      path: '/files'
      fullPath: '/admin/files'
      preLoaderRoute: typeof AdminFilesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminFilesRoute: typeof AdminFilesRoute
  AdminJobsRoute: typeof AdminJobsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPlansRoute: typeof AdminPlansRoute
  AdminProvidersRoute: typeof AdminProvidersRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsageRoute: typeof AdminUsageRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminFilesRoute: AdminFilesRoute,
  AdminJobsRoute: AdminJobsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPlansRoute: AdminPlansRoute,
  AdminProvidersRoute: AdminProvidersRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsageRoute: AdminUsageRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ApiRoute: ApiRoute,
  ContactRoute: ContactRoute,
  CustomDictionaryRoute: CustomDictionaryRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  RealtimeRoute: RealtimeRoute,
  RecordRoute: RecordRoute,
  ReferralRoute: ReferralRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SupportRoute: SupportRoute,
  TranscriptionSettingsRoute: TranscriptionSettingsRoute,
  UploadRoute: UploadRoute,
  CheckoutOrderIdRoute: CheckoutOrderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
